site_name: Roblox Documentation
nav:
    - Roblox Introduction: introduction.md
    - How To parts: part.md
    - Scripts: scripts.md
    - Variables: variables.md
    - Roblox Obby: obby.md
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages: ['lua']
extra_css:
    - css/style.css